import turtle
kalem=turtle.Turtle()
kalem.pencolor("red")
kalem.pensize(5)
kalem.forward(100)
kalem.left(90)
kalem.color("#ace515")
kalem.pensize(10)
kalem.forward(100)
kalem.left(90)
kalem.color("#2259c1")
kalem.pensize(10)
kalem.forward(100)
kalem.left(90)
kalem.pencolor("grey")
kalem.pensize(5)
kalem.forward(100)
turtle.done()